# Generated by Django 6.1.1 on 2026-09-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
