# Generated by Django 6.1.1 on 2026-09-26 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('building', 'Building'), ('completed', 'Completed'), ('paused', 'Paused')], default='planning', max_length=20),
        ),
        migrations.CreateModel(
            name='DevLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('log_type', models.CharField(choices=[('build', 'Build'), ('bug', 'Bug'), ('decision', 'Decision'), ('learning', 'Learning'), ('milestone', 'Milestone')], default='build', max_length=20)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devlogs', to='base.project')),
            ],
        ),
    ]
